name: BlueMarket Pipeline

on:
  push:
    branches: [master]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar código
        uses: actions/checkout@v4

      - name: ⚙️ Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar dependencias
        run: npm ci

      - name: 🔨 Build de la app
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
       - name: 🔍 Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://bluemarket-two.vercel.app
          budgetPath: .github/lighthouse-budget.json
          uploadArtifacts: true