name: BlueMarket Pipeline

on:
  push:
    branches: [master]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar código
        uses: actions/checkout@v4

      - name: ⚙️ Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: 📦 Instalar dependencias
        run: npm ci

      - name: 🔨 Build de la app
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}